name: Build Win Tools
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with: { ref: 3.3.5 }
      - name: Install Boost
        run: |
          Invoke-WebRequest https://github.com/TrinityCore/TrinityCore/releases/download/TDB1200.26021/boost_1_91_0-msvc-14.3-64.exe -OutFile boost_installer.exe
          .\boost_installer.exe /SILENT /SUPPRESSMSGBOXES /DIR="C:\local\boost_1_91_0"
          echo "BOOST_ROOT=C:\local\boost_1_91_0" >> 
      - run: cmake -S . -B build -DTOOLS=1 -DWITHOUT_METRICS=1 -DBOOST_ROOT=C:\local\boost_1_91_0
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: tools-335
          path: build/bin/Release/*.exe